# Customer Churn Analysis

## Importing Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

## Reading CSV File and Creating Df

In [3]:
df = pd.read_csv("Customer_churn_data.csv")
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Suresh Singh,Female,33,Gujarat,Ahmedabad,6,Premium,1517.20,9136.49,Two Year,UPI,Fiber,No,No,Yes,Yes,01-02-2025
1,C1001,Sunita Jain,Male,35,UP,Agra,8,Basic,1796.16,14401.06,Month-to-Month,Cash,Fiber,No,No,No,No,09-03-2025
2,C1002,Priya Gupta,Male,38,Maharashtra,Mumbai,68,Premium,2362.37,160621.88,One Year,Debit Card,Fiber,Yes,No,Yes,No,16-05-2026
3,C1003,Sneha Yadav,Female,45,Gujarat,Ahmedabad,42,Basic,1470.14,61708.05,Month-to-Month,Cash,Fiber,No,No,Yes,No,23-07-2025
4,C1004,Amit Jain,Female,56,Delhi,Delhi,61,Premium,743.43,45399.10,Month-to-Month,UPI,5G,No,No,Yes,Yes,27-12-2025

## Data Profiling

In [4]:
df.shape

(1000000, 18)

1. 1 million rows
2. 18 columns

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Customer_ID            1000000 non-null  str
 1   Customer_Name          979898 non-null   str
 2   Gender                 980033 non-null   str
 3   Age                    1000000 non-null  int64
 4   State                  1000000 non-null  str
 5   City                   1000000 non-null  str
 6   Tenure_Months          1000000 non-null  int64
 7   Subscription_Type      980115 non-null   str
 8   Monthly_Charges        989887 non-null   float64
 9   Total_Charges          980052 non-null   float64
 10  Contract_Type          1000000 non-null  str
 11  Payment_Method         980066 non-null   str
 12  Internet_Service       1000000 non-null  str
 13  Tech_Support           980022 non-null   str
 14  Senior_Citizen         1000000 non-null  str
 15  Dependents             979767 non-null   str
 16  Churn                  1000000 non-null  str
 17  Last_Interaction_Date  1000000 non-null  str
dtypes: float64(2), int64(2), str(14)
memory usage: 217.8 MB

## Missing Values

In [6]:
df.isna().sum()

Customer_ID                  0
Customer_Name            20102
Gender                   19967
Age                          0
State                        0
City                         0
Tenure_Months                0
Subscription_Type        19885
Monthly_Charges          10113
Total_Charges            19948
Contract_Type                0
Payment_Method           19934
Internet_Service             0
Tech_Support             19978
Senior_Citizen               0
Dependents               20233
Churn                        0
Last_Interaction_Date        0
dtype: int64

## Duplicates checking

In [7]:
df.duplicated().sum()

np.int64(0)

# Data Cleaning

In [8]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'City',
       'Tenure_Months', 'Subscription_Type', 'Monthly_Charges',
       'Total_Charges', 'Contract_Type', 'Payment_Method', 'Internet_Service',
       'Tech_Support', 'Senior_Citizen', 'Dependents', 'Churn',
       'Last_Interaction_Date'],
      dtype='str')

## Removing Extra spaces

In [9]:
df = df.apply(lambda x: x.str.strip() if x.dtype=='object' else x)

In [10]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Suresh Singh,Female,33,Gujarat,Ahmedabad,6,Premium,1517.20,9136.49,Two Year,UPI,Fiber,No,No,Yes,Yes,01-02-2025
1,C1001,Sunita Jain,Male,35,UP,Agra,8,Basic,1796.16,14401.06,Month-to-Month,Cash,Fiber,No,No,No,No,09-03-2025
2,C1002,Priya Gupta,Male,38,Maharashtra,Mumbai,68,Premium,2362.37,160621.88,One Year,Debit Card,Fiber,Yes,No,Yes,No,16-05-2026
3,C1003,Sneha Yadav,Female,45,Gujarat,Ahmedabad,42,Basic,1470.14,61708.05,Month-to-Month,Cash,Fiber,No,No,Yes,No,23-07-2025
4,C1004,Amit Jain,Female,56,Delhi,Delhi,61,Premium,743.43,45399.10,Month-to-Month,UPI,5G,No,No,Yes,Yes,27-12-2025

## Change title() case to categorical columns which will not affect the result after changing case.

In [12]:
df.Contract_Type.value_counts()

Contract_Type
Month-to-Month    450039
One Year          300002
Two Year          249959
Name: count, dtype: int64

In [13]:
df.Customer_Name = df.Customer_Name.str.title()
df.Gender = df.Gender.str.title()
df.Subscription_Type = df.Subscription_Type.str.title()
df.Payment_Method = df.Payment_Method.str.title()
df.Tech_Support = df.Tech_Support.str.title()
df.State = df.State.str.title()
df.City = df.City.str.title()
df.Internet_Service = df.Internet_Service.str.title()
df.Senior_Citizen = df.Senior_Citizen.str.title()
df.Churn = df.Churn.str.title()

In [14]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Suresh Singh,Female,33,Gujarat,Ahmedabad,6,Premium,1517.20,9136.49,Two Year,Upi,Fiber,No,No,Yes,Yes,01-02-2025
1,C1001,Sunita Jain,Male,35,Up,Agra,8,Basic,1796.16,14401.06,Month-to-Month,Cash,Fiber,No,No,No,No,09-03-2025
2,C1002,Priya Gupta,Male,38,Maharashtra,Mumbai,68,Premium,2362.37,160621.88,One Year,Debit Card,Fiber,Yes,No,Yes,No,16-05-2026
3,C1003,Sneha Yadav,Female,45,Gujarat,Ahmedabad,42,Basic,1470.14,61708.05,Month-to-Month,Cash,Fiber,No,No,Yes,No,23-07-2025
4,C1004,Amit Jain,Female,56,Delhi,Delhi,61,Premium,743.43,45399.10,Month-to-Month,Upi,5G,No,No,Yes,Yes,27-12-2025

## Checking distinct values and their frequency in categorical columns

In [18]:
df.Subscription_Type.value_counts()

Subscription_Type
Basic       399154
Standard    300405
Premium     280556
Name: count, dtype: int64

In [19]:
df.Gender.value_counts()

Gender
Male      501214
Female    478819
Name: count, dtype: int64

In [20]:
df.Payment_Method.value_counts()

Payment_Method
Upi            249382
Credit Card    221514
Debit Card     220906
Cash           149115
Net Banking    139149
Name: count, dtype: int64

In [21]:
df.Tech_Support.value_counts()

Tech_Support
No     490228
Yes    489794
Name: count, dtype: int64

In [22]:
df.State.value_counts()

State
Up             249622
Maharashtra    249027
Gujarat        167641
Delhi          167155
Karnataka      166555
Name: count, dtype: int64

In [23]:
df.City.value_counts()

City
Noida        83903
Surat        83846
Ahmedabad    83795
Lucknow      83440
Kanpur       83307
Mysuru       83287
Bengaluru    83268
Delhi        83252
Pune         83230
Nagpur       83190
Agra         82875
Mumbai       82607
Name: count, dtype: int64

In [24]:
df.Internet_Service.value_counts()

Internet_Service
Fiber    349884
Dsl      249349
5G       200485
Cable    200282
Name: count, dtype: int64

In [25]:
df.Senior_Citizen.value_counts()

Senior_Citizen
No     806929
Yes    193071
Name: count, dtype: int64

In [26]:
df.Churn.value_counts()

Churn
No     739842
Yes    260158
Name: count, dtype: int64

## Change datatype of columns

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Customer_ID            1000000 non-null  str
 1   Customer_Name          979898 non-null   str
 2   Gender                 980033 non-null   str
 3   Age                    1000000 non-null  int64
 4   State                  1000000 non-null  str
 5   City                   1000000 non-null  str
 6   Tenure_Months          1000000 non-null  int64
 7   Subscription_Type      980115 non-null   str
 8   Monthly_Charges        989887 non-null   float64
 9   Total_Charges          980052 non-null   float64
 10  Contract_Type          1000000 non-null  str
 11  Payment_Method         980066 non-null   str
 12  Internet_Service       1000000 non-null  str
 13  Tech_Support           980022 non-null   str
 14  Senior_Citizen         1000000 non-null  str
 15  Dependents             979767 non-null   str
 16  Churn                  1000000 non-null  str
 17  Last_Interaction_Date  1000000 non-null  str
dtypes: float64(2), int64(2), str(14)
memory usage: 218.4 MB

In [33]:
# All columns has correct datatype except for the Last_Interaction_Date.

df['Last_Interaction_Date'] = pd.to_datetime(df['Last_Interaction_Date'], format='%d-%m-%Y')

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Customer_ID            1000000 non-null  str
 1   Customer_Name          979898 non-null   str
 2   Gender                 980033 non-null   str
 3   Age                    1000000 non-null  int64
 4   State                  1000000 non-null  str
 5   City                   1000000 non-null  str
 6   Tenure_Months          1000000 non-null  int64
 7   Subscription_Type      980115 non-null   str
 8   Monthly_Charges        989887 non-null   float64
 9   Total_Charges          980052 non-null   float64
 10  Contract_Type          1000000 non-null  str
 11  Payment_Method         980066 non-null   str
 12  Internet_Service       1000000 non-null  str
 13  Tech_Support           980022 non-null   str
 14  Senior_Citizen         1000000 non-null  str
 15  Dependents             979767 non-null   str
 16  Churn                  1000000 non-null  str
 17  Last_Interaction_Date  1000000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(13)
memory usage: 208.9 MB

In [35]:
df.head(2)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Suresh Singh,Female,33,Gujarat,Ahmedabad,6,Premium,1517.20,9136.49,Two Year,Upi,Fiber,No,No,Yes,Yes,2025-02-01
1,C1001,Sunita Jain,Male,35,Up,Agra,8,Basic,1796.16,14401.06,Month-to-Month,Cash,Fiber,No,No,No,No,2025-03-09

## Checking invalid data

In [37]:
df.describe().loc[['min', 'max']]

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date
min,18.0,1.0,300.0,257.23,2025-01-01 00:00:00
max,125.0,72.0,2500.0,179995.43,2026-07-04 00:00:00

In [45]:
df.loc[df['Age'] > 100, 'Age'] = np.nan

In [47]:
df.Age.isna().sum()

np.int64(5032)

## Filling missing values / Replacing NaN

In [65]:
df.isna().sum()

Customer_ID                  0
Customer_Name            20102
Gender                   19967
Age                       5032
State                        0
City                         0
Tenure_Months                0
Subscription_Type        19885
Monthly_Charges          10113
Total_Charges            19948
Contract_Type                0
Payment_Method           19934
Internet_Service             0
Tech_Support             19978
Senior_Citizen               0
Dependents               20233
Churn                        0
Last_Interaction_Date        0
dtype: int64

In [68]:
df[df.Customer_Name.isna()]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
69,C1069,NaN,Female,32.0,Delhi,Delhi,72,Standard,816.89,58836.38,Month-to-Month,Upi,Dsl,Yes,No,No,No,2025-12-25
154,C1154,NaN,Female,32.0,Up,Kanpur,17,Standard,2160.35,36735.06,Two Year,Debit Card,5G,Yes,No,Yes,Yes,2025-11-20
261,C1261,NaN,Male,58.0,Gujarat,Ahmedabad,53,Basic,1402.62,74357.45,Month-to-Month,Debit Card,Cable,Yes,No,No,No,2025-09-02
390,C1390,NaN,Female,31.0,Maharashtra,Nagpur,29,Standard,1676.12,48642.40,Month-to-Month,Upi,Dsl,Yes,No,No,No,2025-01-04
441,C1441,NaN,Female,27.0,Gujarat,Ahmedabad,20,Standard,2075.98,41476.13,One Year,Cash,Fiber,Yes,No,No,No,2025-07-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999801,C1000801,NaN,Female,60.0,Up,Lucknow,27,Basic,887.84,23935.17,Two Year,Net Banking,Cable,No,Yes,No,No,2025-12-02
999819,C1000819,NaN,Male,69.0,Karnataka,Mysuru,14,Premium,2421.41,33855.49,Month-to-Month,Credit Card,Cable,Yes,Yes,Yes,No,2025-07-27
999837,C1000837,NaN,Male,36.0,Delhi,Noida,6,Premium,1848.87,11079.82,Two Year,Upi,Fiber,NaN,No,Yes,No,2026-03-15
999902,C1000902,NaN,Male,31.0,Gujarat,Surat,13,Standard,445.10,5767.41,One Year,Debit Card,Cable,No,No,No,No,2026-01-16
999920,C1000920,NaN,Male,69.0,Maharashtra,Pune,35,Premium,2385.96,83472.40,One Year,Cash,Fiber,Yes,Yes,No,No,2025-03-16

In [67]:
df[df.isna().any(axis=1)]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
12,C1012,Kavita Jain,Female,69.0,Maharashtra,Mumbai,31,Basic,NaN,61783.43,Month-to-Month,Debit Card,Fiber,No,Yes,No,No,2025-07-21
22,C1022,Vikas Yadav,Male,50.0,Maharashtra,Pune,8,NaN,1783.63,14235.62,Month-to-Month,Credit Card,Fiber,Yes,No,Yes,Yes,2025-09-23
23,C1023,Abhishek Gupta,NaN,70.0,Maharashtra,Nagpur,49,Standard,NaN,83599.68,Month-to-Month,Cash,5G,No,Yes,Yes,No,2025-02-07
29,C1029,Rohit Yadav,Female,49.0,Up,Lucknow,66,Basic,2493.34,NaN,One Year,Debit Card,Fiber,No,No,Yes,No,2026-07-03
40,C1040,Mohit Gupta,Female,31.0,Karnataka,Mysuru,58,NaN,1006.84,58411.68,Month-to-Month,Upi,Dsl,Yes,No,No,No,2025-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999975,C1000975,Deepak Singh,Male,62.0,Karnataka,Mysuru,36,Basic,548.84,19752.27,Two Year,Upi,Fiber,NaN,No,Yes,No,2025-04-19
999977,C1000977,Kavita Kumar,Female,41.0,Delhi,Delhi,7,NaN,479.57,3380.85,One Year,Cash,Dsl,No,No,Yes,No,2026-06-01
999978,C1000978,Mohit Verma,Male,55.0,Maharashtra,Nagpur,38,Standard,1866.57,NaN,Two Year,Debit Card,5G,No,No,No,No,2026-03-30
999981,C1000981,Amit Singh,Female,24.0,Maharashtra,Mumbai,38,Basic,2014.04,NaN,Month-to-Month,Debit Card,5G,No,No,No,No,2025-11-24
999989,C1000989,Kavita Kumar,Male,55.0,Karnataka,Mysuru,64,Standard,1753.23,NaN,Month-to-Month,Debit Card,Fiber,No,No,No,No,2025-03-09

In [69]:
df.Gender.mode()[0]

'Male'

In [70]:
df.Gender = df.Gender.fillna(df.Gender.mode()[0])

In [61]:
df.Age.median().astype(int)

np.int64(45)

In [71]:
df.Age = df.Age.fillna(df.Age.median().astype(int))

In [55]:
df.Subscription_Type.mode()[0]

'Basic'

In [72]:
df.Subscription_Type = df.Subscription_Type.fillna(df.Subscription_Type.mode()[0])

In [62]:
df.Monthly_Charges.mean().round(2)

np.float64(1401.16)

In [73]:
df.Monthly_Charges = df.Monthly_Charges.fillna(df.Monthly_Charges.mean().round(2))

In [63]:
df.Total_Charges.mean().round(2)

np.float64(51084.94)

In [74]:
df.Total_Charges = df.Total_Charges.fillna(df.Total_Charges.mean().round(2))

In [58]:
df.Payment_Method.mode()[0]

'Upi'

In [75]:
df.Payment_Method = df.Payment_Method.fillna(df.Payment_Method.mode()[0])

In [59]:
df.Tech_Support.mode()[0]

'No'

In [76]:
df.Tech_Support = df.Tech_Support.fillna(df.Tech_Support.mode()[0])

In [60]:
df.Dependents.mode()[0]

'No'

In [77]:
df.Dependents = df.Dependents.fillna(df.Dependents.mode()[0])

In [78]:
df.isna().sum()

Customer_ID                  0
Customer_Name            20102
Gender                       0
Age                          0
State                        0
City                         0
Tenure_Months                0
Subscription_Type            0
Monthly_Charges              0
Total_Charges                0
Contract_Type                0
Payment_Method               0
Internet_Service             0
Tech_Support                 0
Senior_Citizen               0
Dependents                   0
Churn                        0
Last_Interaction_Date        0
dtype: int64

In [79]:
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')

In [80]:
df.isna().sum()

Customer_ID              0
Customer_Name            0
Gender                   0
Age                      0
State                    0
City                     0
Tenure_Months            0
Subscription_Type        0
Monthly_Charges          0
Total_Charges            0
Contract_Type            0
Payment_Method           0
Internet_Service         0
Tech_Support             0
Senior_Citizen           0
Dependents               0
Churn                    0
Last_Interaction_Date    0
dtype: int64

# Feature engineering

## Customer_Value

In [82]:
df['Customer_Value'] = df.Tenure_Months * df.Monthly_Charges

In [83]:
df.head(2)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value
0,C1000,Suresh Singh,Female,33.0,Gujarat,Ahmedabad,6,Premium,1517.20,9136.49,Two Year,Upi,Fiber,No,No,Yes,Yes,2025-02-01,9103.20
1,C1001,Sunita Jain,Male,35.0,Up,Agra,8,Basic,1796.16,14401.06,Month-to-Month,Cash,Fiber,No,No,No,No,2025-03-09,14369.28

## Tenure_Groups

In [85]:
bins = [0, 12, 24, 48, 72]
labels = ["0-12 month", "13-24 month", "25-48 month", "49-72 month"]

df['Tenure_Group'] = pd.cut(
    df['Tenure_Months'], 
    bins=bins, 
    labels=labels, 
    include_lowest=True
)

In [86]:
df['Tenure_Group'].value_counts(dropna=False)

Tenure_Group
25-48 month    333654
49-72 month    332398
0-12 month     167034
13-24 month    166914
Name: count, dtype: int64

## Age_Group

In [87]:
df['Age_Group'] = np.where(df['Age'] >= 60, 'Senior', np.where(df['Age'] >= 30, 'Adult', 'Young'))

In [90]:
df['Age_Group'].value_counts(dropna=False)

Age_Group
Adult     557185
Senior    222117
Young     220698
Name: count, dtype: int64

## Churn_Flag

In [91]:
df['Churn'].value_counts(dropna=False)

Churn
No     739842
Yes    260158
Name: count, dtype: int64

In [92]:
df['Churn_Flag'] = df['Churn'].map({'No':0,'Yes':1})

In [93]:
df['Churn_Flag'].value_counts(dropna=False)

Churn_Flag
0    739842
1    260158
Name: count, dtype: int64

# Final Check

In [96]:
df.isna().sum() # No missing values

Customer_ID              0
Customer_Name            0
Gender                   0
Age                      0
State                    0
City                     0
Tenure_Months            0
Subscription_Type        0
Monthly_Charges          0
Total_Charges            0
Contract_Type            0
Payment_Method           0
Internet_Service         0
Tech_Support             0
Senior_Citizen           0
Dependents               0
Churn                    0
Last_Interaction_Date    0
Customer_Value           0
Tenure_Group             0
Age_Group                0
Churn_Flag               0
dtype: int64

In [98]:
df.duplicated().sum() # No duplicates

np.int64(0)

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 22 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Customer_ID            1000000 non-null  str
 1   Customer_Name          1000000 non-null  str
 2   Gender                 1000000 non-null  str
 3   Age                    1000000 non-null  int64
 4   State                  1000000 non-null  str
 5   City                   1000000 non-null  str
 6   Tenure_Months          1000000 non-null  int64
 7   Subscription_Type      1000000 non-null  str
 8   Monthly_Charges        1000000 non-null  float64
 9   Total_Charges          1000000 non-null  float64
 10  Contract_Type          1000000 non-null  str
 11  Payment_Method         1000000 non-null  str
 12  Internet_Service       1000000 non-null  str
 13  Tech_Support           1000000 non-null  str
 14  Senior_Citizen         1000000 non-null  str
 15  Dependents             1000000 non-null  str
 16  Churn                  1000000 non-null  str
 17  Last_Interaction_Date  1000000 non-null  datetime64[us]
 18  Customer_Value         1000000 non-null  float64
 19  Tenure_Group           1000000 non-null  category
 20  Age_Group              1000000 non-null  str
 21  Churn_Flag             1000000 non-null  int64
dtypes: category(1), datetime64[us](1), float64(3), int64(3), str(14)
memory usage: 237.4 MB

In [105]:
df.describe().round(2)

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date,Customer_Value,Churn_Flag
count,1000000.00,1000000.00,1000000.00,1000000.00,1000000,1000000.00,1000000.00
mean,44.54,36.47,1401.16,51084.94,2025-10-02 16:15:59.759999,51088.11,0.26
min,18.00,1.00,300.00,257.23,2025-01-01 00:00:00,300.11,0.00
25%,31.00,18.00,857.28,19586.10,2025-05-18 00:00:00,19249.36,0.00
50%,45.00,36.00,1401.16,42182.50,2025-10-03 00:00:00,41187.70,0.00
75%,58.00,54.00,1945.88,74557.87,2026-02-17 00:00:00,75509.59,1.00
max,71.00,72.00,2500.00,179995.43,2026-07-04 00:00:00,179997.84,1.00
std,15.55,20.78,631.88,39056.77,NaN,39367.12,0.44

# Save cleaned dataset to csv file

In [106]:
df.to_csv('Cleaned_churn_data.csv', index=False)

# Export to MSSQL